### ISSUE TITLE
The performance of SlowFastR101+8×8+K600 is lower than official data.

### ISSUE THREAD

**Issue by rogercmq** [ShoufaChen/WOO#2]
In the official SlowFast repo, the performance of SlowFastR101+8×8+K600 on AVA2.2 is 29.1 mAP (without E2E) . See [https://github.com/facebookresearch/SlowFast/blob/main/MODEL_ZOO.md#ava](https://github.com/facebookresearch/SlowFast/blob/main/MODEL_ZOO.md#ava)

However, in your paper, the baseline SlowFastR101+8×8+K600 mAP is 27.4. **Is it your re-implementation result?**

![Table 1](https://seikim.com/i/2022/01/17/s8d6rx.png)

**Comment by ShoufaChen** [comment]
A similar issue can be found here: https://github.com/facebookresearch/SlowFast/issues/141.

In summary, the official repo  [does not release the training schedule for R101](https://github.com/facebookresearch/SlowFast/issues/141#issuecomment-608231118). We train R101 by ourselves. 

A similar performance is also achieved [here](https://github.com/facebookresearch/SlowFast/issues/141#issuecomment-723924348).

**Comment by rogercmq** [comment]
Got it! Thx!
